SOURCES = __init__.py \
QGeoApp.py \
basic/file/doDeleteProject.py \
basic/file/doImportData.py \
basic/file/Ui_deleteproject.py \
basic/file/Ui_importdata.py \
basic/help/doAbout.py \
basic/help/Ui_about.py \
basic/projects/doLoadProjectsFile.py \
basic/settings/doOptions.py \
basic/settings/Ui_options.py \
basic/tools/qgeoapputils.py \
modules/pnf/QGeoAppModule.py \
modules/pnf/complexchecks/bahn_alle_checks.py \
modules/pnf/complexchecks/bahn_lagekontrolle.py \
modules/pnf/complexchecks/bahn_maengel.py \
modules/pnf/complexchecks/baugebiet_alle_checks.py \
modules/pnf/complexchecks/baugebiet_checklayer.py \
modules/pnf/complexchecks/baugebiet_lagekontrolle.py \
modules/pnf/complexchecks/baugebiet_maengel.py \
modules/pnf/complexchecks/bestockt_alle_checks.py \
modules/pnf/complexchecks/bestockt_checklayer.py \
modules/pnf/complexchecks/bestockt_lagekontrolle.py \
modules/pnf/complexchecks/bestockt_maengel.py \
modules/pnf/complexchecks/gewaesser_alle_checks.py \
modules/pnf/complexchecks/gewaesser_checklayer.py \
modules/pnf/complexchecks/gewaesser_lagekontrolle.py \
modules/pnf/complexchecks/gewaesser_maengel.py \
modules/pnf/complexchecks/landwirtschaft_alle_checks.py \
modules/pnf/complexchecks/landwirtschaft_checklayer.py \
modules/pnf/complexchecks/landwirtschaft_lagekontrolle.py \
modules/pnf/complexchecks/landwirtschaft_maengel.py \
modules/pnf/complexchecks/perimeterrand_alle_checks.py \
modules/pnf/complexchecks/perimeterrand_checklayer.py \
modules/pnf/complexchecks/perimeterrand_maengel.py \ 
modules/pnf/complexchecks/seltene_objekte_alle_checks.py \
modules/pnf/complexchecks/seltene_objekte_checklayer.py \
modules/pnf/complexchecks/seltene_objekte_lagekontrolle.py \
modules/pnf/complexchecks/seltene_objekte_maengel.py \
modules/pnf/complexchecks/strasse_alle_checks.py \
modules/pnf/complexchecks/strasse_checklayer.py \
modules/pnf/complexchecks/strasse_lagekontrolle.py \
modules/pnf/complexchecks/strasse_maengel.py \
modules/pnf/complexchecks/differenzlayer_anzeigen.py \
modules/pnf/complexchecks/differenzlayer_erzeugen.py \
modules/pnf/complexchecks/doCreateDifferenceLayer.py \
modules/pnf/complexchecks/strassenachsentests_anzeigen.py \
modules/pnf/complexchecks/strassenachsentests_erzeugen.py \
modules/pnf/tools/CheckUtils.py \
modules/pnf/tools/doExportDefects.py \
modules/pnf/tools/doLoadDefects.py \
resources.py

TRANSLATIONS = i18n/QGeoApp_de.ts
