INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'BB.Strasse_Weg');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'BB.Trottoir');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'BB.Verkehrsinsel');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'BB.uebrige_befestigte');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'BB.uebrige_humusierte');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.Laermschutzwand');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.Tunnel_Unterfuehrung_Galerie');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.Bruecke_Passerelle');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.Pfeiler');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.schmaler_Weg');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Strasse', 'EO.Fahrspur');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bahn', 'BB.Bahn');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bahn', 'EO.Laermschutzwand');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bahn', 'EO.Bahnsteig');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bahn', 'EO.Bahngeleise');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bahn', 'EO.Bahngeleise_ueberdeckt');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'BB.Gewaesser.stehendes');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'BB.Gewaesser.fliessendes');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'BB.Schilfguertel');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'EO.eingedoltes_oeffentliches_Gewaesser');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'EO.Bruecke_Passerelle');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'EO.Schwelle');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'EO.Rinnsal');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Gewaesser', 'EO.Quelle');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Gebaeude');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Wasserbecken');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Lagerplatz');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Gebaeudeerschliessung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Parkplatz');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.uebrige_befestigte');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'BB.Gartenanlage');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.Mauer');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.unterirdisches_Gebaeude');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.uebriger_Gebaeudeteil');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.wichtige_Treppe');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.Reservoir');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.Unterstand');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bebautes Gebiet', 'EO.Silo_Turm_Gasometer');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bestockte Flaeche', 'BB.geschlossener_Wald');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bestockte Flaeche', 'BB.Hecke');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bestockte Flaeche', 'BB.uebrige_bestockte');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Bestockte Flaeche', 'EO.schmale_bestockte_Flaeche');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Landwirtschaft', 'BB.Acker_Wiese');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Landwirtschaft', 'BB.Weide');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Landwirtschaft', 'BB.Reben');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Landwirtschaft', 'BB.Obstkultur');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Landwirtschaft', 'BB.uebrige_Intensivkultur');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Flugplatz');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Sportanlage_befestigt');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Boeschungsbauwerk');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Parkanlage_humusiert');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Sportanlage_humusiert');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Friedhof');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Hoch_Flachmoor');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.uebrige_humusierte');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Parkanlage_bestockt');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Fels');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Gletscher_Firn');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Geroell_Sand');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Steinbruch');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Kiesgrube');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.Deponie');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.uebriger_Abbau');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'BB.uebrige_vegetationslose');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Brunnen');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Hochkamin');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Denkmal');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Mast_Antenne');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Mast_Leitung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Aussichtsturm');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Uferverbauung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Lawinenverbauung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.massiver_Sockel');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Ruine_archaeologisches_Objekt');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Landungssteg');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.einzelner_Fels');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Hochspannungsfreileitung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Druckleitung');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Luftseilbahn');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Gondelbahn_Sesselbahn');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Materialseilbahn');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Skilift');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Faehre');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Grotte_Hoehleneingang');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Achse');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.wichtiger_Einzelbaum');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Seltene Objekte', 'EO.Bildstock_Kruzifix');

INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Perimeterrand',  'BB.Differenzen am Perimeterrand');
INSERT INTO type_of_defects (gruppe, art_txt)  VALUES ('Perimeterrand',  'EO.Differenzen am Perimeterrand');
